// Auto-generated by Windjammer — do not edit manually.
// Rust tests in `tests/*.rs` are discovered automatically (no manual `tests/lib.rs` registration).

#[cfg(test)]
pub mod cross_file_trait_test;
#[cfg(test)]
pub mod ecs_inspector_panel_test;
#[cfg(test)]
pub mod examples_integration_test;
#[cfg(test)]
pub mod generated_components_test;
#[cfg(test)]
pub mod integration_ui_examples;
#[cfg(test)]
pub mod profiler_foundation_test;
